spring.application.name=backend
spring.datasource.url=jdbc:h2:file:./data/cloudstorage
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000

# File Storage Configuration
file.upload-dir=uploads

# Server port
server.port=8080

# Multipart Configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Gmail SMTP Configuration for OTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# REPLACE THIS WITH YOUR GMAIL ADDRESS THAT GENERATED THE APP PASSWORD
spring.mail.username=kumar12345abhinek@gmail.com
spring.mail.password=gkxrvuaksiqzjeyu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
